In [6]:
import warp as wp
import numpy as np

num_points = 1024

@wp.kernel
def length(points: wp.array(dtype=wp.vec3),
           lengths: wp.array(dtype=float)):

    # thread index
    tid = wp.tid()

    # compute distance of each point from origin
    lengths[tid] = wp.length(points[tid])


# allocate an array of 3d points
points = wp.array(np.random.rand(num_points, 3), dtype=wp.vec3)
lengths = wp.zeros(num_points, dtype=float)
print("points:", points)
print("points shape", points.shape)
# launch kernel
wp.launch(kernel=length,
          dim=len(points),
          inputs=[points, lengths])
print("lengths.shape:",lengths.shape)
print(lengths)

points: [[0.21311295 0.21613573 0.43213648]
 [0.26252964 0.41892794 0.03120678]
 [0.10489726 0.5313923  0.19744273]
 ...
 [0.6289035  0.7898621  0.06346463]
 [0.8062457  0.16132316 0.25107595]
 [0.65138865 0.45150954 0.9629215 ]]
points shape (1024,)
lengths.shape: (1024,)
[0.52808493 0.49537492 0.5765109  ... 1.011647   0.8597072  1.2471511 ]
