In [2]:
import warp as wp
import numpy as np

num_points = 1024

@wp.kernel
def length(points: wp.array(dtype=wp.vec3),
           lengths: wp.array(dtype=float)):

    # thread index
    tid = wp.tid()

    # compute distance of each point from origin
    lengths[tid] = wp.length(points[tid])


# allocate an array of 3d points
points = wp.array(np.random.rand(num_points, 3), dtype=wp.vec3)
lengths = wp.zeros(num_points, dtype=float)
print("points:", points)
print("points shape", points.shape)
# launch kernel
wp.launch(kernel=length,
          dim=len(points),
          inputs=[points, lengths])
print("lengths.shape:",lengths.shape)
print(lengths)

Warp 1.4.1 initialized:
   CUDA Toolkit 11.8, Driver 12.2
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
     "cuda:1"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
     "cuda:2"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
     "cuda:3"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
   CUDA peer access:
     Not supported
   Kernel cache:
     /home/jiahao/.cache/warp/1.4.1
points: [[0.68533355 0.6196526  0.51668906]
 [0.9969159  0.20321104 0.64668804]
 [0.16280068 0.55827886 0.9407387 ]
 ...
 [0.8335893  0.00702002 0.90483177]
 [0.0020878  0.7493751  0.885826  ]
 [0.834012   0.8195862  0.9396033 ]]
points shape (1024,)
Module __main__ fdb5417 load on device 'cuda:0' took 1.67 ms  (cached)
lengths.shape: (1024,)
[1.0585929 1.2055461 1.1059695 ... 1.2303011 1.1602824 1.5000507]


In [3]:
a=wp.vec2(3,4)
wp.length(a)

5.0